apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcp-secret-store
spec:
  provider:
    gcpsm:
      projectID: project-8fadb4d4-cc54-44ca-80c
      auth:
        workloadIdentity:
          clusterName: imagep-gke
          clusterLocation: asia-southeast1-a
          serviceAccountRef:
            name: sa
            namespace: eso