apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: image-apis-secret
  namespace: imageapis
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: image-apis-secret
    creationPolicy: Owner
  data:
    - secretKey: redis-password
      remoteRef:
        key: redis-password
