apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa
  namespace: imageapis
  annotations:
    iam.gke.io/gcp-service-account: imagep-image-apis-gsa@project-8fadb4d4-cc54-44ca-80c.iam.gserviceaccount.com
