apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa
  namespace: imagecompressor
  annotations:
    iam.gke.io/gcp-service-account: imagep-image-processor-gsa@project-8fadb4d4-cc54-44ca-80c.iam.gserviceaccount.com
