apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: main-pool
  namespace: kafka
  labels:
    strimzi.io/cluster: imagep
spec:
  replicas: 3
  roles:
    - controller
    - broker
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: 2Gi
        class: standard-rwo
        deleteClaim: true
  resources:
    requests:
      memory: 1536Mi
    limits:
      memory: 2048Mi
  jvmOptions:
    -Xms: 1024m
    -Xmx: 1024m
---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: imagep
  namespace: kafka
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
spec:
  clusterCa:
    validityDays: 3650
    renewalDays: 30
  clientsCa:
    validityDays: 3650
    renewalDays: 30
  kafkaExporter:
    readinessProbe:
      initialDelaySeconds: 10
      timeoutSeconds: 5
    livenessProbe:
      initialDelaySeconds: 10
      timeoutSeconds: 5
    topicRegex: ".*"
    groupRegex: ".*"
  kafka:
    version: 4.0.0
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false

    config:
      log.retention.hours: 24
      default.replication.factor: 3
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.min.isr: 2
      min.insync.replicas: 2

  entityOperator:
    topicOperator: {}
    userOperator: {}
