apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: bootstrap
  namespace: argocd
spec:
  description: Platform bootstrap components (operators, controllers)

  sourceRepos:
    - https://github.com/zhunismp/imagep-backend.git
    - https://charts.external-secrets.io
    - https://strimzi.io/charts

  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cluster
  namespace: argocd
spec:
  description: Cluster components

  sourceRepos:
    - https://github.com/zhunismp/imagep-backend.git

  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: '*'
      kind: '*'