apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
spec:
  project: default

  sources:
    - repoURL: https://charts.external-secrets.io
      chart: external-secrets
      targetRevision: 0.10.5
      helm:
        values: |
          serviceAccount:
            create: false
            name: sa

    - repoURL: https://github.com/zhunismp/imagep-backend.git
      targetRevision: master
      path: k8s/bootstrap/external-secrets

  destination:
    server: https://kubernetes.default.svc
    namespace: eso

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
