apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-controller
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/zhunismp/imagep-backend.git
    targetRevision: master
    path: infrastructure/external-secret

  destination:
    server: https://kubernetes.default.svc
    namespace: eso

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
