apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: image-apis
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/zhunismp/imagep-backend.git
    targetRevision: master
    path: k8s/apps/image-apis

  destination:
    server: https://kubernetes.default.svc
    namespace: imageapis

  syncPolicy:
    automated:
      prune: true
      selfHeal: true