apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-compressor-deployment
  namespace: imagecompressor
  labels:
    app: image-compressor-deployment
spec:
  selector:
    matchLabels:
      app: image-compressor-pod
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: image-compressor-pod
    spec:
      serviceAccountName: sa
      containers:
        - name: image-compressor
          image: zhunismp/image-compressor:35e2c49a16da09a63b11e2a364cc372ed86ebfd3
          ports:
            - containerPort: 8080
              name: http
          envFrom:
            - configMapRef:
                name: image-compressor-config
            - secretRef:
                name: image-compressor-secret
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
          livenessProbe:
            exec:
              command: ["sh", "-c", "exit 0"]
            initialDelaySeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 10
          readinessProbe:
            exec:
              command: ["sh", "-c", "exit 0"]
            initialDelaySeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 10
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: image-compressor-svc
  namespace: imagecompressor
spec:
  selector:
    app: image-compressor-pod
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  template:
    spec:
      containers:
        - image: zhunismp/image-compressor:35e2c49a16da09a63b11e2a364cc372ed86ebfd3
