apiVersion: v1
kind: ConfigMap
metadata:
  name: image-apis-config
  namespace: imageapis
data:
  HOST: "0.0.0.0"
  PORT: "8080"

  KAFKA_ADDRESS: "imagep-kafka-bootstrap.kafka.svc.cluster.local:9092"

  REDIS_ADDRESS: "redis-master.redis.svc.cluster.local:6379"
  REDIS_DB: "0"

  APP_NAME: "image-apis"
  ENVIRONMENT: "production"
  BASE_API_PREFIX: "/api/v1"
  MAX_FILES: "100"
  POLLING_INTERVAL: "2000"
  FRONTEND_HOST: "http://localhost:3000"